### ISSUE TITLE
Redirection vers show

### ISSUE THREAD

**Issue by victornicolet** [aymericbouzy/balise#107]
Je pense que d'un point de vue navigation, ca n'est pas toujours intéressant de rediriger vers show quand on créé un objet : par exemple pour les budgets je préférerais revenir à l'index, surtout que ce que  je viens de créer est vide. On devrait être redirigé vers show lorsqu'on a probablement des actions à faire sur l'objet que show nous permet.
Qu'est-ce que vous en pensez ?

**Comment by aymericbouzy** [comment]
Oui je suis d'accord ! Et c'est très facile à modifier.
