### ISSUE TITLE
bug #336bd9233b vignettes pour nom de binets très longs

### ISSUE THREAD

**Issue by aymericbouzy** [aymericbouzy/balise#123]
si tu as besoin @victornicolet, on peut faire un helper qui calcule la taille de police nécessaire et la mets en propriété style. Si tu as une autre idée, n'hésite pas ;) ça doit pouvoir se faire en javascript aussi.

**Comment by victornicolet** [comment]
J'ai fait le helper dans la PR que je viens de proposer. Le problème est résolu si on merge, et si ca fonctionne. J'ai essayé avec des noms de binets assez longs.

**Comment by aymericbouzy** [comment]
oui ça marche sur chrome ... mais pas sur safari. Je ne sais pas pourquoi.

**Comment by victornicolet** [comment]
Mais pourtant c'est juste du Php et du css .. hmm. Ok je vais creuser

**Comment by aymericbouzy** [comment]
Pardon pardon j'ai dis de la merde ! ça marche très bien. désolé.

**Comment by victornicolet** [comment]
Ok :)
