### ISSUE TITLE
Contacter quelqu'un par mail

### ISSUE THREAD

**Issue by Newbienathou** [aymericbouzy/balise#128]
Plusieurs retours concernant l'envoi des mails. Quand on clique sur contact ça force l'ouverture de la boîte mail qui est parfois celle qui n'est pas le plus utilisé (outlook, hotmail, ...). Étienne conseille de faire comme sur frankiz où tu vois l'adresse mail que tu peux soit copié coller, soit cliquer dessus pour envoyer un mail.

**Comment by aymericbouzy** [comment]
Donc faire une page pour chaque personne, avec son adresse mail pour le contacter : on pourrait aussi y mettre tous les binets dont il est administrateur.

**Comment by Newbienathou** [comment]
Je suis sensé faire quoi ?

Nathan

**Comment by aymericbouzy** [comment]
désolé je me suis trompé, donc je t'ai dé-assigné : en fait il faut que je crée la page, et ensuite il faudra que Victor la remplisse.
