### ISSUE TITLE
Surcouche de conseils liés à une subvention

### ISSUE THREAD

**Issue by Newbienathou** [aymericbouzy/balise#129]
Faire une modale quand on rentre une opération liée à une subvention pour dire la démarche à suivre (poser la facture à la Kès, puis récupérer le chèque). La démarche varie selon les binets subventionner donc ça serait ultime que chacun puisse choisir le contenu

**Comment by aymericbouzy** [comment]
Il faudrait qu'on décide plus précisément à quel endroit on voit ces informations : tu proposes après la création d'une opération, mais ca veut dire qu'on l'aura a chaque fois : ça risque de devenir chiant.

**Comment by aymericbouzy** [comment]
par contre ici @Newbienathou, ce serait bien que tu nous proposes quelque chose de plus précis :)

**Comment by Newbienathou** [comment]
Dans le mail précédent, il ne faut pas lire binets subventionner mais binets subventionneurs, merci la correction automatique.
L’idée est de préciser la marche à suivre, voici ce qui était dans l’IK pour le forum

Donc après avoir fait une opération liée à une subvention, on aurait une modale qui s’ouvrirait pour expliquer ça. On pourrait faire la même chose avec les dépôts de chèque en expliquant qu’il faut aller les déposer en les photocopiants…

Nathan

**Comment by aymericbouzy** [comment]
Si tu réponds au mail, en fait ça répond à github : si tu veux mettre des images, mets-les plutôt en répondant directement sur github, apparemment il a du mal sinon.
J'ai bien compris ce que tu voulais dire pour la démarche. Mais je ne suis pas d'accord avec ta solution, ou en tout cas elle est incomplète, comme je te l'avais dit dans mon premier message. Voilà deux problèmes : 
* si je fais des opérations toutes les semaines, j'ai compris la démarche à suivre. Donc cette modal me fait chier. Ce serait bien qu'elle apparaisse seulement la première fois par exemple.
* si j'ai quitté la modal, et que je veux y revenir, comment je fais ? où est-ce que je retrouve cette information : à côté de mes opérations en attente de validation ? dans la vue de la vague de subventions ? sur la page du binet subventionneur ? au niveau de ma demande de subventions ? sur une page qui regroupe ces informations pour tous les binets subventionneurs ? à mon avis, il faut pouvoir retrouver l'information à plusieurs de ces endroits, mais peut-être pas tous.
j'aurais aimé que tu te poses toutes ces questions toi-même et que tu en donnes la solution.

**Comment by aymericbouzy** [comment]
autre problème : si je crée une opération qui se rapporte à plusieurs demandes de subventions, pour des démarches différentes : quelle modal j'affiche, qu'est-ce que je fais des informations de l'autre vague qui n'ont pas été affichées ? ...

**Comment by Newbienathou** [comment]
Ouch, ça a fait mal !

Je n’avais pas pensé aux points que tu soulèves. Pour lever la difficulté, ça pourrait être dans la partie subventions (forme à préciser : page indépendante, modal, …) et après le dépôt d’une telle opération, l’ouverture d’une fenêtre, comme celle qu’on a actuellement en haut à droite quand on se connecte où qu’on fait une opération, précisant où on peut retrouver ces informations.

**Comment by aymericbouzy** [comment]
ok il faudra qu'on en discute ensemble ce n'est pas clair du tout là.

**Comment by victornicolet** [comment]
On peut fermer cette issue
