### ISSUE TITLE
Création d'un texte lié à la vague de subvention

### ISSUE THREAD

**Issue by Newbienathou** [aymericbouzy/balise#130]
Pouvoir associer un texte à la création d'une vague de subvention (pour préciser les destinataires de la vagues et les critères) ainsi qu'un texte lié à la publication de la vague : cf article IK)

**Comment by aymericbouzy** [comment]
J'avais imaginé qu'on pouvait utiliser le champ question aussi pour dire qui est éligible, mais pas de probleme, on pourra rajouter ca.
