### ISSUE TITLE
Liste des opérations en attente de validation par la Kès

### ISSUE THREAD

**Issue by Newbienathou** [aymericbouzy/balise#132]
Quand on est kessier, on voit la demande de validation mais on n'a pas le résumé des subventions attribuées pour le binet en question, ce serait bien de le rajouter pour aider au processus de décision

**Comment by aymericbouzy** [comment]
Il faudrait aussi rajouter dans index opération la liste des opérations en attente de validation par la Kès.

**Comment by victornicolet** [comment]
C'est bon ça je crois.

**Comment by aymericbouzy** [comment]
ah bon ? non, un binet ne voit plus ses opérations en attente de validation par la Kès.

**Comment by victornicolet** [comment]
Ah oui je n'ai pas relu ton commentaire.
