### ISSUE TITLE
Date d'utilisation de la subvention

### ISSUE THREAD

**Issue by Newbienathou** [aymericbouzy/balise#133]
Mettre en information la date d'utilisation de la subvention pour un poste de dépense

**Comment by aymericbouzy** [comment]
oulah j'ai fais n'importe quoi désolé ... on est tous les deux assignés en fait.

**Comment by Newbienathou** [comment]
On peut la fermer celle là?

**Comment by aymericbouzy** [comment]
On la fermera quand on aura mergé help-text avec dedans le conseil aux binets subventionneurs de demander la date d'utilisation de la subvention.

**Comment by Newbienathou** [comment]
Je viens de faire le commit dans help-text

**Comment by victornicolet** [comment]
C'est bon ?

**Comment by aymericbouzy** [comment]
oui, même si ce n'est pas encore en ligne, ça le sera bientôt de toute façon.
