### ISSUE TITLE
mettre la facture en fichier joint

### ISSUE THREAD

**Issue by aymericbouzy** [aymericbouzy/balise#144]
Faut il le faire ou non ? sous quelle forme ?

**Comment by victornicolet** [comment]
Il faut voir ce qui se fait déjà chez le BR, mais ca peut être intéressant.
Après c'est loin d'être prioritaire...

**Comment by Newbienathou** [comment]
À voir, j’en ai un peu discuté avec Barbry, la question est est-ce que les gens font faire la démarche de numériser leurs factures.

**Comment by aymericbouzy** [comment]
Tu nous avais pas dit que l'original des factures devaient être de toute façon conservées a la Kès ?

**Comment by Newbienathou** [comment]
En effet, elles y sont, plus ou moins bien rangées selon que cela soit un binet avec chéquier ou sans chéquier (les avec chéquiers ont un classeur perso)

**Comment by aymericbouzy** [comment]
S'ils n'ont pas besoin de l'original ca prend tout son sens : ca veut dire qu'on peut faire toutes les démarches en ligne, et la Kès peut faire toutes les validations sans avoir à manipuler des papiers, elle a simplement a les imprimer et les mettre dans un classeur a la fin. Sinon c'est quand même beaucoup moins utile objectivement.
