### ISSUE TITLE
Problème lors de l'ovuerture d'une vague

### ISSUE THREAD

**Issue by victornicolet** [aymericbouzy/balise#166]
J'ai une erreur 400 lorsque j'essaie d'ouvrir une vague.

Voilà le message debug :

———————————
**** Ne pas modifier cette partie ****

URL demandée :					/beta/binet/x-subventions/2013/wave/9/open
Browser :							Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36
personne connectée :				victor.nicolet.0@gmail.com
état de la variable $_POST :			array(0) {
}

état de la variable $_SESSION :		array(12) {
  ["csrf_token"]=>
  string(32) "d3a1bff64d045119d276227d2e246a43"
  ["tag_to_create"]=>
  NULL
  ["operation_entry_form"]=>
  NULL
  ["return_to"]=>
  string(37) "beta/binet/alfa-romeo/2013/budget/new"
  ["stored_errors"]=>
  array(2) {
    [0]=>
    string(36) "Tu n'as pas rempli le nom du budget."
    [1]=>
    string(40) "Tu n'as pas rempli le montant du budget."
  }
  ["tag_form"]=>
  NULL
  ["student"]=>
  string(1) "1"
  ["admin_form"]=>
  NULL
  ["binet_form"]=>
  NULL
  ["wave"]=>
  array(1) {
    ["errors"]=>
    array(0) {
    }
  }
  ["error"]=>
  NULL
  ["wave_errors"]=>
  NULL
}

état de la variable $_GET :			array(2) {
  ["controller"]=>
  string(5) "error"
  ["action"]=>
  string(3) "400"
}

**Comment by aymericbouzy** [comment]
Tu as bien rajouté les 4 nouveaux champs des vagues en base de donnée ?

**Comment by aymericbouzy** [comment]
Il faut aussi faire l’url rewriting : http://localhost:3000/beta/url_rewriting.php <http://localhost:3000/beta/url_rewriting.php>

**Comment by victornicolet** [comment]
Ok c'était le .htaccess
