### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Newbienathou** [aymericbouzy/balise#183]
Regardez les rapports de bug qu'on a vu apparaître pendant la discussion avec les kessières

**Comment by aymericbouzy** [comment]
C'est pas ouf cette issue : on ne se souvient plus de quoi ça parle. Il vaudrait mieux disséquer le rapport de bug reçu, et faire une issue par bug différent que l'on a reçu.

**Comment by aymericbouzy** [comment]
Du coup on fait quoi, je ferme cette issue ?

**Comment by Newbienathou** [comment]
Si on a décortiqué et ouvert les issues pour les rapports de bug, oui
