### ISSUE TITLE
Demander des subventions pour la promo suivante

### ISSUE THREAD

**Issue by victornicolet** [aymericbouzy/balise#197]
TODOs :

- créer un formulaire de transmission des budgets d'une année sur l'autre ( liste de budgets à sélectionner)
- ajouter la possibilité de valdier des opérations pour le mandat suivant.

**Comment by victornicolet** [comment]
TODOs :
- créer un formulaire de transmission des budgets d'une année sur l'autre ( liste de budgets à sélectionner)
- mettre là case à cocher du formuaire de requête de subventions sous un autre format : switch entre deux promotions.
- ajouter la possibilité de valdier des opérations pour le mandat suivant.

**Comment by victornicolet** [comment]
Je fais de la merde.. j'essaie den ous assigner tous les deux.

**Comment by aymericbouzy** [comment]
oui je me suis rendu compte aussi que c'était pas possible ^^
