### ISSUE TITLE
Affichage vague de subventions

### ISSUE THREAD

**Issue by Newbienathou** [aymericbouzy/balise#218]
Bug d'affichage pour un binet subventionner dans le cas de nombre long (voir capture d'écran par mail)

**Comment by aymericbouzy** [comment]
@Newbienathou n'hésites pas à faire directement une issue github en mettant la capture d'écran dedans : ça nous envoie un mail de toute façon. Comme ça on se fait moins spamé, tout est centralisé au même endroit, et ça te prend moins de temps ;)

**Comment by Newbienathou** [comment]
Je croyais qu’on pouvait pas mettre d’image, c’est ce que tu m’avais dis une fois

**Comment by aymericbouzy** [comment]
ah bon ? on avait du mal se comprendre. Tu as juste à faire un drag and drop dans ton commentaire. Par exemple : 
![capture d ecran 2015-03-06 a 01 48 31](https://cloud.githubusercontent.com/assets/8168981/6523956/01e9ab10-c3f5-11e4-9a05-ebc69935b3f4.png)

Je pense que tu confonds avec autre chose. J'avais dit qu'on ne pouvait pas faire un lien sur le site tel que quand tu cliques dessus, ça ouvre un nouveau mail avec des pièces jointes, mais ça n'a rien à voir.

**Comment by aymericbouzy** [comment]
ah bon ? je n'ai pas vu la correction que tu as faite :(

**Comment by victornicolet** [comment]
Elle était dans multiple corrections

Le ven. 6 mars 2015 à 15:54, Aymeric Bouzy <notifications@github.com> a
écrit :

**Comment by aymericbouzy** [comment]
Va voir en ligne, il y a encore le bug : le problème, c'est l'espace en trop après ":" dans demandes acceptées.

**Comment by aymericbouzy** [comment]
et en plus j'avais pas fait gaffe, mais tu as utilisé is_empty au lieu de !is_empty :)

**Comment by victornicolet** [comment]
Si le bug est résolu : il n'y a plus d'espace entre les barre info et la liste des requête, mais on voit la totalité de la première requête. Tout à l'heure elel était partiellement masquée.
Mon problème là dedans c'est qu'on affiche d'abord la liste dans le html, puis la barre, que je remets au dessus. Mais même si ca peut sembler bizarre il n'y a pas de "bug", on peut accéder à toutes les requêtes.
Je pourrais ajouter du javascript poru recalculer l'espace, ou faire deux fois la boucle mais j'ai estiméque ca n'en valait pas la peine.

Ok je corrige ça.

**Comment by aymericbouzy** [comment]
ahhh ok, j'avais pas ça comme ça pour le bug. je croyais que c'était le texte avec 2 points au milieu qui était bizarre. si tu enlèves l'espace après les 2 points, c'est plus joli.

**Comment by victornicolet** [comment]
OU est-ce que j'ai utlisé is_empty ?

**Comment by victornicolet** [comment]
Ah c'est bon.
