### ISSUE TITLE
Wave index : onglet navigation inexistant, même si brouillon existant

### ISSUE THREAD

**Issue by victornicolet** [aymericbouzy/balise#220]
Je suis un binet subventionneur : au départ l'onglet vague de subventions n'existe pas.
Je créé ma première vague, et je la laisse en brouillon. L'onglet vagues de subventions n'existe toujours pas ! Impossible de retrouver mon brouillon.

**Comment by aymericbouzy** [comment]
ah oui merde, effectivement je n'avais pas pensé à ça. je m'en occupe !
