### ISSUE TITLE
Bug après création de tab (on voit les subventions espérées)

### ISSUE THREAD

**Issue by Newbienathou** [aymericbouzy/balise#232]
![capture d ecran 2015-03-09 a 14 15 24](https://cloud.githubusercontent.com/assets/9706794/6571257/869b6a4c-c706-11e4-9b35-97d89acfb89c.png)

**Comment by victornicolet** [comment]
Nathan fais des issues un peu mieux expliquées stp ! Je comprends mais j'ai besoin de réfléchir, et j'aime pas.
