### ISSUE TITLE
Créer des boutons avec modal de confirmation

### ISSUE THREAD

**Issue by aymericbouzy** [aymericbouzy/balise#251]
Certaines actions irréversibles pourraient avoir une modal qui permettent de confirmer : on peut utiliser la classe modal-sm de bootstrap pour ça. Le mieux serait d'adapter le helper button pour qu'il prenne un paramètre optionnel "modal-text" : si ce paramètre est non vide, le button a une modal, sinon il fait directement un lien.
il faudra voir comment faire pour les boutons de request index, qui sont un peu différents.

**Comment by victornicolet** [comment]
Ok bonne idée je m'en occuppedès que possible. L'idée c'est que le bouton visible sur la page active une modale, et le bouton réel de confirmation est dans la modale.

**Comment by aymericbouzy** [comment]
Tout a fait ! Mais au niveau de l'interface de programmation, il faudrait que ce soit complètement transparent.
