### ISSUE TITLE
Changer le switch dans les demandes de subventions pour le rendre plus clair

### ISSUE THREAD

**Issue by Newbienathou** [aymericbouzy/balise#252]
Rajouter un tipps lors d'une demande de subventions pour bien préciser comment on fait pour demander la subvention pour la promo suivante

**Comment by aymericbouzy** [comment]
On ne peut pas mettre ça dans l'aide plutôt ?

**Comment by aymericbouzy** [comment]
Le problème en fait c'est que les gens ne comprennent pas que c'est un switch : il faut faire quelque chose de plus clair.
