### ISSUE TITLE
Rendre plus clair ce que sont les opérations à valider

### ISSUE THREAD

**Issue by aymericbouzy** [aymericbouzy/balise#255]
Les opérations à valider peuvent être des opérations créées par quelqu'un d'autre mais aussi des opérations non encore ajoutées au budget. Il faut que cela soit plus clair pour les binets. Des propositions ?

**Comment by victornicolet** [comment]
J'ai expliqué le truc à quelqu'un et ça lui semblait clair. En fait je pense que dire que "Validations" c'ets la même chose quelque soit l'origine de l'opération ca porte à confusion.
On pourrait séparer les deux, au moins visuellement dans la liste des "Opérations en attente de traitement" (on peut trouver un nom qui reflète le fait qu'il faille répartir le montant de l'opération entre différents budgets ?).

**Comment by aymericbouzy** [comment]
En fait avec la nouvelle navigation, il suffit de changer la manière dont on appelle les choses et ce sera tout de suite beaucoup plus clair. Je fais un commit.
