### ISSUE TITLE
Navigation et sidebar

### ISSUE THREAD

**Issue by victornicolet** [aymericbouzy/balise#261]
Je trouve qu'afficher le nom du binet qu'on regarde dans la sidebar n'a pas vraiment de sens. Pour moi, ca devrait être le nom du binet pour lequel on agit. 
On ne pourrait pas avoir une variable qui stocke le binet courant ?
C'est comme ça que je l'avais imaginé au début.

**Comment by aymericbouzy** [comment]
Je ne suis pas d'accord. Je vois ce que tu veux dire, mais à nouveau, ce serait tenter de cacher comment le site est fait en réalité, et à chaque fois on s'est rendu compte que cela menait à des confusions. Je pense que c'est bien de garder cette cohérence. En revanche, je pense qu'il faudrait afficher non pas le nom du binet, mais le binet plus la promo. Par ailleurs, il faudrait mettre le lien vers le show binet dans la sidebar, et pouvoir changer la promo dans la sidéra aussi, plutôt que cela soit restreint à budget index et opération index. Egalement, le fait de choisir un des binets qui nous appartient  ne devrait pas se faire à cet endroit là : il faudrait plutôt que ce soit dans le header, qui contient des informations spécifiques à la personne connectée. Qu'en pensez-vous ?

**Comment by Newbienathou** [comment]
Assez d’accord avec Aymeric mais je ne visualise pas tout
