### ISSUE TITLE
Retirer lien vers les créneaux d'inscription à la kès

### ISSUE THREAD

**Issue by aymericbouzy** [aymericbouzy/balise#281]
dans home/welcome, il y a un lien qu'il faut retirer.

**Comment by Newbienathou** [comment]
On peut mettre un lien vers le wikiX à la place ? Ou vers les tutos vidéos ?

**Comment by victornicolet** [comment]
Bonne idée je pense. Et on a notre lien sur Frankiz  ?
Bon j'ai été assez absent cette semaine je n'arrête pas de bouger mais je
me remets sur le projet des mardi soir quand je serai bien installé !

**Comment by Newbienathou** [comment]
J’ai mis le lien wikiX sur Frankiz. Petite question, est-ce qu’Alexandre et Pierre voient ces mails ?

**Comment by victornicolet** [comment]
@AlexandreGuinaudeau  suit le repo sur Github donc il doit voir ces conversations ?

**Comment by AlexandreGuinaudeau** [comment]
Oui, je vois bien tous vos messages, mais je suis assez occupé en ce moment ^^
En tout cas les binettes ont prévu d'organiser une réunion pour les prez/trez, pour leur demander de mettre à jour leurs subventions (et en expliquer le fonctionnement). Ce serait sans doute la semaine après les pâles.

**Comment by aymericbouzy** [comment]
Du coup Nathan tu te sens de faire la PR ? le fichier a modifier c'est view/home/welcome.php

**Comment by Newbienathou** [comment]
Oui dès que j’arrive à configurer MAMP, je crois que le problème via de git et pas de MAMP : je n’ai visiblement pas le dernier fichier car à chaque fois que je synchronise, il m’indique qu’il y a un fichier qui a changé (le .htaccess)

**Comment by Newbienathou** [comment]
J'ai fais les modifications nécessaire, il y a juste un peu de mise en page à faire (centrer la vidéo) que je n'ose pas faire, tu pourras regarder @victornicolet ?

Je n'ai pas mis les vidéos sur Github, elles sont sur ma dropbox à laquelle vous avez accès. Il faut télécharger tout le contenu du fichier video et le mettre dans videos.

**Comment by Newbienathou** [comment]
J'oubliais, la branche s'appelle welcome-page

**Comment by aymericbouzy** [comment]
Tu veux bien faire ta PR ? Tu commences le texte d'explication par WIP (work in progress), et comme ça on sait que ce n'est pas fini, mais que tu as besoin de notre avis, ou d'aide, etc ... En fait ce n'est pas à nous qu'il faut donner l'accès au contenu du fichier vidéo mais à @AlexandreGuinaudeau qui devra le mettre en ligne ... Bon Victor ça l'arrangera peut-être d'en avoir au moins une pour faire le front end, c'est vrai ;)

**Comment by Newbienathou** [comment]
Désolé de ne pas l’avoir fait mais je ne sais pas pourquoi, j’ai reçu tous mes mails avec 7h de retard… Je crois que gmail fait des siennes.

Nathan

**Comment by Newbienathou** [comment]
Et rassure toi, j’ai donné les droits d’accès de ma dropbox à Alexandre et j’ai même mis le lien du fichier qui contient les vidéos sur frankiz

**Comment by aymericbouzy** [comment]
Ok parfait ! 
Je me disais : est-ce que ça va être logique pour les gens de se deconnecter pour pouvoir voir les vidéos ? Est-ce que ça serait pas mieux de les mettre dans une nouvelle page home/video à laquelle on peut accéder depuis home ?

**Comment by victornicolet** [comment]
C'est bien aussi qu'elle soient accessibles depuis l'accueil pour les
personnes qui viennent "juste voir" aussi. On peut faire les deux je pense.

Le mar. 31 mars 2015 à 08:03, Aymeric Bouzy <notifications@github.com> a
écrit :

> Ok parfait !
> Je me disais : est-ce que ça va être logique pour les gens de se
> deconnecter pour pouvoir voir les vidéos ? Est-ce que ça serait pas mieux
> de les mettre dans une nouvelle page home/video à laquelle on peut accéder
> depuis home ?
>
>
>

**Comment by aymericbouzy** [comment]
On peut aussi donner accès à la page où elles sont sans connection (DRY).
