### ISSUE TITLE
Incohérence des subventions attendues

### ISSUE THREAD

**Issue by ilai-deutel** [aymericbouzy/balise#297]
Salut !
Pour les subventions *Forum novembre* (qui n'ont pas encore été acceptées), pour certains budgets, le montant diffère entre les subventions attendues sur la page *Demandes de subventions* du binet et les subventions attendues sur la page du budget correspondant (budget n°227 par exemple).

**Comment by victornicolet** [comment]
il ne s'agit pas du même montant. Les montants qui figurent sur les pages
de budgets correspondants sont les montants en subventions que le binet
espère en totalité (avec les subventions Kès en plus, etc. ).
En plus ce montant est totalement indicatif et sert juste repère pour la
trésorerie.
Par contre, ce qu'on voit dans la demande de subventions, c'est spécifique
à une vagues, et c'est "officiel".

Dis-moi si je n'ai pas bien compris le problème !

Le mar. 26 mai 2015 à 16:12, Ilaï Deutel <notifications@github.com> a
écrit :

**Comment by ilai-deutel** [comment]
Il s'agit peut-être juste d'un problème de libellé alors. Pour le budget 227 dont je parle (qui correspond à une seule vague de subventions) il y a marqué :

**Subventions attendues pour ce budget**
40

Alors que sur la page de la demande (request n°81), il y a :

**Opérations liées à cette subvention**
0 utilisés, +50 accordés, +50 demandés

alors que la demande de subvention est toujours *en attente*. Ou alors j'ai mal compris, et dans ce cas-là au temps pour moi !

**Comment by aymericbouzy** [comment]
le terme "Subventions attendues" désigne les subventions que le binet espère recevoir pour ce budget sur l'ensemble de l'année par l'ensemble des binets subventionneurs. Il est utile au binet pour concevoir son budget, et aux binets subventionneurs pour savoir si le binet espère recevoir des subventions d'autres instances. Le montant attendu pour le budget peut être modifier tant que le budget est modifiable, c'est à dire tant qu'aucune subvention n'y est associé. J'espère que ça répond à ta question !
