### ISSUE TITLE
Affichage des notifications

### ISSUE THREAD

**Issue by aymericbouzy** [aymericbouzy/balise#30]
![screen shot 2015-01-24 at 09 34 45](https://cloud.githubusercontent.com/assets/8168981/5886685/6285ba04-a3ac-11e4-9990-060fbb47eebe.png)

je pense qu'il faut que tu rajoutes un z-index

**Comment by aymericbouzy** [comment]
Ou plutôt que tu restreignes l'espace prévu pour le formulaire.

**Comment by victornicolet** [comment]
De toute façon il faudra revoir ça... parce que normalement l'affichage du formulaire est restreint. J'ai donc du faire une erreur quelque part.

**Comment by aymericbouzy** [comment]
C'est moi qui l'ai créé le formulaire.

**Comment by victornicolet** [comment]
Ah ok, il suffit le le mettre entre deux div avec la classe form-container

**Comment by aymericbouzy** [comment]
Je te laisserai le faire de toute façon, ce formulaire est vraiment dégueux.

**Comment by victornicolet** [comment]
Je veux bien le code html en attendant de pouvoir afficher moi-même les pages pour les bugs d'affichage. Mais je pense que je vais devoir pouvoir voir le site moi-même à un moment ou un autre..

**Comment by aymericbouzy** [comment]
Oui bien sur. Si tu veux je passe chez toi ce soir et je te configure tout pour que tu fasses tourner le site en local. tu vas voir, c'est encore hyper bugué, tu vas me faire des issues toutes les 5 minutes ;)

**Comment by victornicolet** [comment]
Je suis à Dijon chez ma soeur pour l'instant, je sais pas encore quand
est-ce que je rentre, mais je te redis.
