### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by victornicolet** [aymericbouzy/balise#33]
Dans la branche nice-home-index, je n'arrive pas à charger les fichiers css, simplement parce qu'ils va les chercher dans assets et pas beta/assets. Tu peux corriger ça ?

Voilà le screeenshot de l'erreur :
![screenshot from 2015-01-25 21 35 01](https://cloud.githubusercontent.com/assets/9047901/5893181/7c8a741a-a4da-11e4-8d05-8f3bda0da12f.png)

**Comment by aymericbouzy** [comment]
Le problème est résolu dans la PR que je t'ai faite.

**Comment by victornicolet** [comment]
Ok, j'ai changé manuellemnt dans la branche ui-updates juste pour faire des tests : j'y penserai au moment de merger.

**Comment by aymericbouzy** [comment]
Du coup tu peux merger master dans ta branche, et ça corrigera le problème
