### ISSUE TITLE
show wave

### ISSUE THREAD

**Issue by aymericbouzy** [aymericbouzy/balise#66]
Initialement j'avais prévu de faire 2 show wave : 
* celui que tu as déjà fait, qui aurait du être en view/wave/show.php. Il s'agit des informations publiques sur la vague de subvention (dates, état actuel, montant total alloué, lien de redirection vers le détail des subventions perçues par chaque binet, avec total du montant alloué affiché ...)
* un deuxième en view/binet/wave/show.php qui sert pour l'administration de la vague par le binet qui l'a créée. Les administrateurs y retrouvent des statistiques intéressantes (total de l'argent dépensé, total de l'argent accordé, nombre de binets qui ont fait une demande, ...), peuvent modifier les paramètres de la vague, faire l'étude des demandes de subventions, etc ...

A mieux y réfléchir, je pense qu'il vaut mieux fusionner ces deux pages, mais en tout cas il manque encore beaucoup d'informations pour le binet qui a créé la vague. Il faudrait faire quelque chose un peu comme le show binet.
Si tu as besoin qu'on travaille d'abord sur un cahier des charges un peu plus précis, je suis dispo.

**Comment by victornicolet** [comment]
J'ai lancé la branche, mais je m'arrête la pour aujourd'hui : j'ai bougé le code existant de binet/wave a wave .
Mais est-ce que binet/wave/show.php continuera a exister ?

**Comment by aymericbouzy** [comment]
Je propose plutôt de garder uniquement binet/wave/show si ça ne t'ennuie pas.

**Comment by victornicolet** [comment]
Ok je ferai comme ça demain.

Le Mon Feb 09 2015 at 12:37:57 AM, Aymeric Bouzy <notifications@github.com>
a écrit :

Je propose plutôt de garder uniquement binet/wave/show si ça ne t'ennuie
