### ISSUE TITLE
Lier dépenses

### ISSUE THREAD

**Issue by Newbienathou** [aymericbouzy/balise#75]
Rajouter dans le champ « payé par », dans « opérations » , « Virement Kès » et  « Virement Corps »
Aussi, le champ «  payé par » n’est pas censé exister que pour les dépenses ?

**Comment by victornicolet** [comment]
On peut ajotuer un choix vide dans le choix de celui qui paie ?

**Comment by Newbienathou** [comment]
Oui, mais ça serait cool de pouvoir rajouter les virements corps, Kès, DFS éventuellement (je ne sais pas si ça existe).

Nathan
