### ISSUE TITLE
In request model

### ISSUE THREAD

**Issue by victornicolet** [aymericbouzy/balise#79]
<b>Fatal error</b>:  Uncaught exception 'ErrorException' with message 'Undefined offset: 0' in /home/nicolet/balise/htdocs/beta/model/request.php:34

**Comment by aymericbouzy** [comment]
C’est parce que tu as créé une demande de subvention sans faire de demande de subvention : il n’y a aucun objet subsidy associé.
Il faut que je rajoute un truc pour l’interdire dans la création d’une demande.

**Comment by victornicolet** [comment]
ok !

**Comment by victornicolet** [comment]
Est-ce que la création de vagues fonctionne chez toi ?

**Comment by aymericbouzy** [comment]
en tout cas elle a marché sur balise.bin ... qu'est-ce qui ne marche pas pour toi ?

**Comment by victornicolet** [comment]
QUand je veux créer une vague je suis redirigé sur cette adresse : 
http://localhost:3000/beta/binet/kes/2013/wave/show
Donc une erreur..et rien n'est créé en bdd

**Comment by aymericbouzy** [comment]
tu peux m'envoyer le mail bug_report ? ça me permettra de voir les données de session.

**Comment by victornicolet** [comment]
Du coup le problème c'est maintenant de contrôler qu'on ne créé pas de demande sans subsidy ?

**Comment by aymericbouzy** [comment]
Je suis en train de m’en occuper.
