### ISSUE TITLE
Signe des montants calculés d'une dépense

### ISSUE THREAD

**Issue by aymericbouzy** [aymericbouzy/balise#85]
signe positif au lieu d'être négatif.

**Comment by Newbienathou** [comment]
Actuellement, on doit cocher uniquement si c’est une dépense, ce serait pas mieux de devoir cocher dans tout les cas, que ce soit dépense ou recette car actuellement, les recettes sont implicites.

**Comment by aymericbouzy** [comment]
tu veux dire avoir un select avec 2 options par exemple ?

**Comment by Newbienathou** [comment]
Oui, une option dépense et une recette (pour les opérations)

**Comment by aymericbouzy** [comment]
ok fais une autre issue pour ce problème.

**Comment by victornicolet** [comment]
C'est bon c'est résolu, tu confirmes @aymericbouzy
