### ISSUE TITLE
Lier opérations au budget

### ISSUE THREAD

**Issue by Newbienathou** [aymericbouzy/balise#89]
Problème pour remplir les champs pour lier une opération au budget

**Comment by aymericbouzy** [comment]
Ce n'est pas le problème de les remplir : en fait c'est tellement moche qu'on ne comprend pas où sont les champs et ce qu'il faut faire. Donc il faut faire un joli formulaire beaucoup plus compréhensible.

**Comment by aymericbouzy** [comment]
Ok je l'ai retrouvé, je m'en occupe.

**Comment by victornicolet** [comment]
Non j'avais fait un formulaire pour la création de budgets ej crois, avec qqch pour sélectionner des tags. Celui là n'a encore jamais été fait ou je ne m'en souviens plus.

**Comment by victornicolet** [comment]
Tu fais quelque chose de plus intuitif ?

**Comment by aymericbouzy** [comment]
bah, non pas vraiment, je reprends ton code. Attends, je vais pusher tu pourras voir.

**Comment by victornicolet** [comment]
Ok merci

**Comment by victornicolet** [comment]
Ok, dès que tu as fini je reprends ton code, ou sinon je créé ma branche à partir de la tienne.

**Comment by aymericbouzy** [comment]
bah en gros j'ai fini. Je voulais juste modifier la somme pour que ce ne soit pas le total mais la différence au total attendu. Je trouve que ça simplifie pour remplir formulaire.

**Comment by victornicolet** [comment]
Justement j'allais suggérer

**Comment by victornicolet** [comment]
Je crois que le problème est résolu ?
