### ISSUE TITLE
In show wave

### ISSUE THREAD

**Issue by victornicolet** [aymericbouzy/balise#90]
Je ne comprends pas d'ou l'errreur vient :+1: 
<b>Fatal error</b>:  Uncaught exception 'ErrorException' with message 'Undefined index: state' in /home/nicolet/balise/htdocs/beta/view/binet/wave/show.php:3

Lorsque j'essaie de charger la page. Même chose poour l'index "binet"

**Comment by aymericbouzy** [comment]
ça dit que le tableau $wave n'a pas de valeur associée à la clé "state". ce tableau est définit dans controller/binet/wave.php dans case "show":
Est-ce que tu as ce problème sur master ou sur ta branche ?

**Comment by victornicolet** [comment]
Sur ma branche
