### ISSUE TITLE
Midnight issue

### ISSUE THREAD

**Issue by victornicolet** [aymericbouzy/balise#92]
J'ai créé une vague de subvention ou la date limite des demandes était aujourd'hui. 
j'ai eu un bug (sur master) : l'index "granted_amount" n'est pas défini dans le modèle.

(je n'ai plus le message de bug, pour travailler j'ai changé la date d'expiration des subventions).

**Comment by aymericbouzy** [comment]
midnight issue ^^ ok faudrait réessayer pour savoir exactement ce qui ne va pas.
